name: Deploy React App to AKS

on:
  push:
    branches:
      - master

env:
  ACR_NAME: mycalculator
  ACR_LOGIN_SERVER: mycalculator.azurecr.io
  IMAGE_NAME: calculator

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Log in to ACR
      run: |
        az acr login --name $ACR_NAME

    - name: Build and push Docker image with unique tag
      run: |
        IMAGE_TAG=${{ github.sha }}
        docker build -t $ACR_LOGIN_SERVER/$IMAGE_NAME:$IMAGE_TAG .
        docker push $ACR_LOGIN_SERVER/$IMAGE_NAME:$IMAGE_TAG
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

    - name: Set AKS context
      uses: azure/aks-set-context@v3
      with:
        resource-group: mycalculator
        cluster-name: myakscluster

    - name: Update Kubernetes deployment with new image
      run: |
        kubectl set image deployment/calculator-deployment calculator=$ACR_LOGIN_SERVER/$IMAGE_NAME:$IMAGE_TAG
